method: grid
program: src/main.py  
command:
  - mpirun
  - -np
  - "8"
  - python
  - ${program}
  - ${args}
parameters:
  set:
    values:
      # - {"dt": 0.1, "T": 1.0, "u_coeff": 10.0, "h_type": "h=0"} #test
      # - {"dt": 0.2, "T": 1.0, "u_coeff": 10.0, "h_type": "h=0"} #test

      # - {"dt": 0.1, "T": 100.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.01, "T": 100.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.1, "T": 10.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.01, "T": 10.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.001, "T": 10.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.1, "T": 1.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.01, "T": 1.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.001, "T": 1.0, "u_coeff": 10.0, "h_type": "h=0"}
      # - {"dt": 0.0001, "T": 1.0, "u_coeff": 10.0, "h_type": "h=0"}
      # # ze źródłem:
      # - {"dt": 0.1, "T": 100.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.01, "T": 100.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.1, "T": 10.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.01, "T": 10.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.001, "T": 10.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.1, "T": 1.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.01, "T": 1.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.001, "T": 1.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}
      # - {"dt": 0.0001, "T": 1.0, "u_coeff": 10.0, "h_type": "h_sinusoidal"}

      - {"dt": 0.1, "T": 1000.0, "u_coeff": 10.0, "h_type": "h=0"}

      - {"dt": 0.001, "T": 1.0, "u_coeff": 1.0, "h_type": "h=0"}
      - {"dt": 0.01, "T": 10.0, "u_coeff": 1.0, "h_type": "h=0"}

      - {"dt": 0.001, "T": 1.0, "u_coeff": 1.0, "h_type": "h_sinusoidal"}
      - {"dt": 0.01, "T": 10.0, "u_coeff": 1.0, "h_type": "h_sinusoidal"}